package config

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
)

// decodeTOML decodes b over cfg (which arrives pre-filled with defaults, so a
// file only needs to carry the keys the user changed) and rejects unknown keys
// with their names so typos surface loudly instead of being silently ignored.
func decodeTOML(b []byte, cfg *Config) error {
	md, err := toml.Decode(string(b), cfg)
	if err != nil {
		return err
	}
	if und := md.Undecoded(); len(und) > 0 {
		var keys []string
		for _, k := range und {
			keys = append(keys, k.String())
		}
		return fmt.Errorf("unknown key(s): %s — fix the file or run `qfn config init` to regenerate it", strings.Join(keys, ", "))
	}
	return nil
}

// Render serializes cfg back to the canonical commented template. Comments are
// regenerated, not preserved: the comment set is fixed and self-documenting, so
// hand-written extra comments do not survive `qfn config set` (documented).
func Render(cfg Config) string {
	var b strings.Builder
	b.WriteString("# QFN-PGX configuration — generated by `qfn init` / `qfn config`.\n")
	b.WriteString("# Every value is validated on save and on load; fix the line and rerun if\n")
	b.WriteString("# qfn complains here. `qfn config init` regenerates this file from defaults.\n\n")

	b.WriteString("[paths]\n")
	line(&b, "hf_cache", q(cfg.Paths.HFCache), "Hugging Face cache holding the checkpoint snapshot")
	line(&b, "state_dir", q(cfg.Paths.StateDir), "qfn state: bench history, lockout state, service inventory")
	b.WriteString("\n[engine]\n")
	line(&b, "mode", q(cfg.Engine.Mode), `"nvfp4" = checkpoint as published; "hybrid" = fp8 side layers (+20% decode, run qfn prepare-hybrid first)`)
	line(&b, "prefix_cache", tf(cfg.Engine.PrefixCache), "repeated prefixes skip prefill (~14s -> ~1.4s TTFT on a 20k prefix)")
	line(&b, "exact_topk", tf(cfg.Engine.ExactTopK), "deterministic greedy at T=0; costs ~10-40% on long prefills")
	line(&b, "ctx", n(cfg.Engine.Ctx), "max context; >262144 requires yarn=true (validated to 500000)")
	line(&b, "yarn", tf(cfg.Engine.Yarn), "YaRN rope scaling (factor 4) to go past the native window")
	line(&b, "mtp", n(cfg.Engine.MTP), "MTP speculative tokens (0 = off; 2 is this checkpoint's measured peak)")
	line(&b, "seqs", n(cfg.Engine.Seqs), "max concurrent sequences — do not leave at 1-2 when measuring throughput")
	line(&b, "gpu_mem", f(cfg.Engine.GpuMem), "fraction of the 128 GB unified pool for weights+KV (max 0.875; 0.80 for long-running service)")
	line(&b, "kv_dtype", q(cfg.Engine.KVDtype), `keep "auto" (bf16); fp8 is refused by the QSA layers`)
	line(&b, "prewarm", tf(cfg.Engine.Prewarm), "stream the ~48 GiB PLE table once at boot to warm the page cache")
	line(&b, "workers", n(cfg.Engine.Workers), "threads for the PLE mmap gather")
	line(&b, "cpuset", q(cfg.Engine.CPUSet), `docker --cpuset-cpus ("" = unpinned; experiment, unverified on this lane)`)
	line(&b, "extra", q(cfg.Engine.Extra), "extra vllm flags passed verbatim, appended last (argparse last-wins)")
	line(&b, "port", n(cfg.Engine.Port), "host port published for the engine API")
	line(&b, "bind", q(cfg.Engine.Bind), `"127.0.0.1" keeps the engine reachable only through the qfn proxy; "0.0.0.0" exposes it directly`)
	line(&b, "lockdown", tf(cfg.Engine.Lockdown), "start vLLM with a generated --api-key only the qfn proxy holds (stored age-encrypted)")
	line(&b, "container_mem_cap", q(cfg.Engine.ContainerMem), `docker --memory ("" = none, correct here: PLE mmap needs the page cache; see qfn doctor)`)
	line(&b, "image", q(cfg.Engine.Image), "engine image built from engine/Dockerfile")
	line(&b, "model", q(cfg.Engine.Model), "checkpoint id (resolved to the local snapshot dir)")
	line(&b, "name", q(cfg.Engine.Name), "docker container name")
	b.WriteString("\n[serve]\n")
	line(&b, "port", n(cfg.Serve.Port), "web console + proxy port (ssh -L 8799:localhost:8799 <spark> to reach it)")
	line(&b, "bind", q(cfg.Serve.Bind), "console bind; 0.0.0.0 = reachable on the LAN (auth is always on; open the port in the firewall, e.g. `sudo ufw allow 8799`)")
	line(&b, "proxy", tf(cfg.Serve.Proxy), "mount /v1/* as the OpenAI-compatible front door on this port")
	line(&b, "max_prompt_tokens", n(cfg.Serve.MaxPromptTokens), "0 = no ceiling; >0 rejects over-long prompts via a /tokenize pre-check")
	line(&b, "sampling_defaults", tf(cfg.Serve.SamplingDefaults), "true = proxy fills omitted temperature/top_p/top_k from the checkpoint's generation_config.json")
	line(&b, "auth_enabled", tf(cfg.Serve.AuthEnabled), "password gate set by `qfn init` (credentials.age); cannot be disabled off-loopback")
	line(&b, "require_api_key", tf(cfg.Serve.RequireAPIKey), "future: reject cookie-only /v1 calls once named machine keys ship")
	if len(cfg.Serve.APIKeys) > 0 {
		for _, k := range cfg.Serve.APIKeys {
			b.WriteString("\n[[serve.api_keys]]\n")
			b.WriteString(fmt.Sprintf("name = %s\nkey_hash = %s\ncreated = %s\n", q(k.Name), q(k.KeyHash), q(k.Created)))
		}
	}
	b.WriteString("\n[service]\n")
	line(&b, "serve_always_on", tf(cfg.Service.ServeAlwaysOn), "qfn service install makes the console reboot-persistent")
	line(&b, "engine_autostart", tf(cfg.Service.EngineAutostart), "also enable the engine unit so the model boots with the box")
	b.WriteString("\n[meta]\n")
	line(&b, "first_run_done", tf(cfg.Meta.FirstRunDone), "false re-opens the wizard on next run")
	line(&b, "default_profile", q(cfg.Meta.DefaultProfile), "profile applied by `qfn up` with no argument")
	return b.String()
}

func line(b *strings.Builder, key, val, comment string) {
	b.WriteString(fmt.Sprintf("%s = %s  # %s\n", key, val, comment))
}

func q(s string) string { return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"` }
func tf(v bool) string  { if v { return "true" }; return "false" }
func n(v int) string    { return strconv.Itoa(v) }
func f(v float64) string { return strconv.FormatFloat(v, 'g', -1, 64) }
